// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const authAuthenticationResponse = z.lazy(() => {
  return z.object({
    redirectTo: z.string().optional(),
  });
});

/**
 *
 * @typedef  {AuthAuthenticationResponse} authAuthenticationResponse
 * @property {string}
 */
export type AuthAuthenticationResponse = z.infer<typeof authAuthenticationResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const authAuthenticationResponseResponse = z.lazy(() => {
  return z
    .object({
      redirectTo: z.string().optional(),
    })
    .transform((data) => ({
      redirectTo: data['redirectTo'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const authAuthenticationResponseRequest = z.lazy(() => {
  return z
    .object({
      redirectTo: z.string().optional(),
    })
    .transform((data) => ({
      redirectTo: data['redirectTo'],
    }));
});
