// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { WalletService } from './services/wallet';

export * from './services/wallet';

export * from './http';
export { Environment } from './http/environment';

export class ByteNiteWalletApi {
  public readonly wallet: WalletService;

  constructor(public config: SdkConfig) {
    this.wallet = new WalletService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.wallet.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.wallet.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.wallet.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.wallet.token = token;
  }

  set apiKey(apiKey: string) {
    this.wallet.apiKey = apiKey;
  }

  set apiKeyHeader(apiKeyHeader: string) {
    this.wallet.apiKeyHeader = apiKeyHeader;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
