// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const responses = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    version: z.string().optional(),
    schema: z.any().optional(),
  });
});

/**
 *
 * @typedef  {Responses} responses
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {any}
 */
export type Responses = z.infer<typeof responses>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const responsesResponse = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      version: z.string().optional(),
      schema: z.any().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      version: data['version'],
      schema: data['schema'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const responsesRequest = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      version: z.string().optional(),
      schema: z.any().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      version: data['version'],
      schema: data['schema'],
    }));
});
