// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { CommonVersion, commonVersion, commonVersionRequest, commonVersionResponse } from './common-version';

/**
 * The shape of the model inside the application code - what the users use
 */
export const responses = z.lazy(() => {
  return z.object({
    version: commonVersion.optional(),
  });
});

/**
 *
 * @typedef  {Responses} responses
 * @property {CommonVersion} - Version of the distributed app, including revision.
 */
export type Responses = z.infer<typeof responses>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const responsesResponse = z.lazy(() => {
  return z
    .object({
      version: commonVersionResponse.optional(),
    })
    .transform((data) => ({
      version: data['version'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const responsesRequest = z.lazy(() => {
  return z
    .object({
      version: commonVersionRequest.optional(),
    })
    .transform((data) => ({
      version: data['version'],
    }));
});
