// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const commonRole = z.union([
  z.literal('ROLE_NONE'),
  z.literal('ROLE_USER'),
  z.literal('ROLE_DEVELOPER'),
  z.literal('ROLE_ADMIN'),
]);

export type CommonRole = z.infer<typeof commonRole>;
