// This file was generated by liblab | https://liblab.com/

import { ByteNiteAuthApi } from 'bytenite auth api';

(async () => {
  const byteNiteAuthApi = new ByteNiteAuthApi({
    token: 'YOUR_TOKEN',
  });

  const { data } = await byteNiteAuthApi.auth.authSkipLogin({
    loginChallenge: 'loginChallenge',
  });

  console.log(data);
})();
