// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const commonDeviceRequirements = z.lazy(() => {
  return z.object({
    minCpu: z.number().optional(),
    minMemory: z.number().optional(),
  });
});

/**
 * DeviceRequirements represents the minimum hardware requirements for running the app/engine.
 * @typedef  {CommonDeviceRequirements} commonDeviceRequirements - DeviceRequirements represents the minimum hardware requirements for running the app/engine. - DeviceRequirements represents the minimum hardware requirements for running the app/engine.
 * @property {number} - Minimum number of CPU cores required to run the app/engine.
 * @property {number} - Minimum amount of RAM (GB) required to run the app.
 */
export type CommonDeviceRequirements = z.infer<typeof commonDeviceRequirements>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const commonDeviceRequirementsResponse = z.lazy(() => {
  return z
    .object({
      minCpu: z.number().optional(),
      minMemory: z.number().optional(),
    })
    .transform((data) => ({
      minCpu: data['minCpu'],
      minMemory: data['minMemory'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const commonDeviceRequirementsRequest = z.lazy(() => {
  return z
    .object({
      minCpu: z.number().optional(),
      minMemory: z.number().optional(),
    })
    .transform((data) => ({
      minCpu: data['minCpu'],
      minMemory: data['minMemory'],
    }));
});
