// This file was generated by liblab | https://liblab.com/

import { ByteNiteWalletApi } from 'bytenite wallet api';

(async () => {
  const byteNiteWalletApi = new ByteNiteWalletApi({
    token: 'YOUR_TOKEN',
  });

  const { data } = await byteNiteWalletApi.wallet.walletGetAccountInfo();

  console.log(data);
})();
