// This file was generated by liblab | https://liblab.com/

export interface WalletGetExchangeRateParams {
  currency?: string;
  currencyAmount?: number;
  amount?: number;
}

export interface WalletPayoutHistoryParams {
  limit?: number;
  offset?: number;
}

export interface WalletGetTransactionListParams {
  paginationLimit?: number;
  paginationOffset?: number;
  orderBy?: string;
}
