// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { JobsService } from './services/jobs';
import { EventsService } from './services/events';
import { InfoService } from './services/info';
import { LogsService } from './services/logs';
import { SchemaService } from './services/schema';
import { StatsService } from './services/stats';

export * from './services/jobs';
export * from './services/events';
export * from './services/info';
export * from './services/logs';
export * from './services/schema';
export * from './services/stats';
export * from './services/common';

export * from './http';
export { Environment } from './http/environment';

export class ByteNiteJobsApi {
  public readonly jobs: JobsService;

  public readonly events: EventsService;

  public readonly info: InfoService;

  public readonly logs: LogsService;

  public readonly schema: SchemaService;

  public readonly stats: StatsService;

  constructor(public config: SdkConfig) {
    this.jobs = new JobsService(this.config);

    this.events = new EventsService(this.config);

    this.info = new InfoService(this.config);

    this.logs = new LogsService(this.config);

    this.schema = new SchemaService(this.config);

    this.stats = new StatsService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.jobs.baseUrl = baseUrl;
    this.events.baseUrl = baseUrl;
    this.info.baseUrl = baseUrl;
    this.logs.baseUrl = baseUrl;
    this.schema.baseUrl = baseUrl;
    this.stats.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.jobs.baseUrl = environment;
    this.events.baseUrl = environment;
    this.info.baseUrl = environment;
    this.logs.baseUrl = environment;
    this.schema.baseUrl = environment;
    this.stats.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.jobs.timeoutMs = timeoutMs;
    this.events.timeoutMs = timeoutMs;
    this.info.timeoutMs = timeoutMs;
    this.logs.timeoutMs = timeoutMs;
    this.schema.timeoutMs = timeoutMs;
    this.stats.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.jobs.token = token;
    this.events.token = token;
    this.info.token = token;
    this.logs.token = token;
    this.schema.token = token;
    this.stats.token = token;
  }

  set apiKey(apiKey: string) {
    this.jobs.apiKey = apiKey;
    this.events.apiKey = apiKey;
    this.info.apiKey = apiKey;
    this.logs.apiKey = apiKey;
    this.schema.apiKey = apiKey;
    this.stats.apiKey = apiKey;
  }

  set apiKeyHeader(apiKeyHeader: string) {
    this.jobs.apiKeyHeader = apiKeyHeader;
    this.events.apiKeyHeader = apiKeyHeader;
    this.info.apiKeyHeader = apiKeyHeader;
    this.logs.apiKeyHeader = apiKeyHeader;
    this.schema.apiKeyHeader = apiKeyHeader;
    this.stats.apiKeyHeader = apiKeyHeader;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
