// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const bytenitewalletApiRedeemCouponRequest = z.lazy(() => {
  return z.object({
    couponCode: z.string().optional(),
  });
});

/**
 *
 * @typedef  {BytenitewalletApiRedeemCouponRequest} bytenitewalletApiRedeemCouponRequest
 * @property {string}
 */
export type BytenitewalletApiRedeemCouponRequest = z.infer<typeof bytenitewalletApiRedeemCouponRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const bytenitewalletApiRedeemCouponRequestResponse = z.lazy(() => {
  return z
    .object({
      couponCode: z.string().optional(),
    })
    .transform((data) => ({
      couponCode: data['couponCode'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const bytenitewalletApiRedeemCouponRequestRequest = z.lazy(() => {
  return z
    .object({
      couponCode: z.string().optional(),
    })
    .transform((data) => ({
      couponCode: data['couponCode'],
    }));
});
