// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const commonFilterCondition = z.union([
  z.literal('FILTER_CONDITION_EQ'),
  z.literal('FILTER_CONDITION_NEQ'),
  z.literal('FILTER_CONDITION_GT'),
  z.literal('FILTER_CONDITION_GTE'),
  z.literal('FILTER_CONDITION_LT'),
  z.literal('FILTER_CONDITION_LTE'),
  z.literal('FILTER_CONDITION_ARRAY_CONTAINS'),
  z.literal('FILTER_CONDITION_ARRAY_CONTAINS_ANY'),
  z.literal('FILTER_CONDITION_IN'),
  z.literal('FILTER_CONDITION_NOT_IN'),
  z.literal('FILTER_CONDITION_LIKE'),
]);

export type CommonFilterCondition = z.infer<typeof commonFilterCondition>;
