// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const planPlanState = z.union([z.literal('NEW'), z.literal('ENABLED'), z.literal('DISABLED')]);

export type PlanPlanState = z.infer<typeof planPlanState>;
