// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const protobufAny = z.lazy(() => {
  return z.object({
    _type: z.string().optional(),
  });
});

/**
 *
 * @typedef  {ProtobufAny} protobufAny
 * @property {string}
 */
export type ProtobufAny = z.infer<typeof protobufAny>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const protobufAnyResponse = z.lazy(() => {
  return z
    .object({
      '@type': z.string().optional(),
    })
    .transform((data) => ({
      _type: data['@type'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const protobufAnyRequest = z.lazy(() => {
  return z
    .object({
      _type: z.string().optional(),
    })
    .transform((data) => ({
      '@type': data['_type'],
    }));
});
