// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const todoState = z.union([
  z.literal('NEW'),
  z.literal('PENDING_VERIFICATION'),
  z.literal('INFO_REQUIRED'),
  z.literal('SENT'),
  z.literal('CONFIRMED'),
  z.literal('BOUNCED'),
  z.literal('FAILED'),
]);

export type TodoState = z.infer<typeof todoState>;
