// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const walletTopUpRequestState = z.union([
  z.literal('NEW'),
  z.literal('PENDING'),
  z.literal('CONFIRMED'),
  z.literal('CANCELED'),
  z.literal('FAILED'),
]);

export type WalletTopUpRequestState = z.infer<typeof walletTopUpRequestState>;
