// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const walletApiTopUpRequestParams = z.lazy(() => {
  return z.object({
    currencyAmount: z.string().optional(),
    currency: z.string().optional(),
    amount: z.string().optional(),
  });
});

/**
 *
 * @typedef  {WalletApiTopUpRequestParams} walletApiTopUpRequestParams
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type WalletApiTopUpRequestParams = z.infer<typeof walletApiTopUpRequestParams>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const walletApiTopUpRequestParamsResponse = z.lazy(() => {
  return z
    .object({
      currencyAmount: z.string().optional(),
      currency: z.string().optional(),
      amount: z.string().optional(),
    })
    .transform((data) => ({
      currencyAmount: data['currencyAmount'],
      currency: data['currency'],
      amount: data['amount'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const walletApiTopUpRequestParamsRequest = z.lazy(() => {
  return z
    .object({
      currencyAmount: z.string().optional(),
      currency: z.string().optional(),
      amount: z.string().optional(),
    })
    .transform((data) => ({
      currencyAmount: data['currencyAmount'],
      currency: data['currency'],
      amount: data['amount'],
    }));
});
