// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  CommonPaginatedResponse,
  commonPaginatedResponse,
  commonPaginatedResponseRequest,
  commonPaginatedResponseResponse,
} from './common-paginated-response';
import {
  BytenitewalletTransaction,
  bytenitewalletTransaction,
  bytenitewalletTransactionRequest,
  bytenitewalletTransactionResponse,
} from './bytenitewallet-transaction';

/**
 * The shape of the model inside the application code - what the users use
 */
export const walletTransactionHistoryResponse = z.lazy(() => {
  return z.object({
    pagination: commonPaginatedResponse.optional(),
    data: z.array(bytenitewalletTransaction).optional(),
  });
});

/**
 *
 * @typedef  {WalletTransactionHistoryResponse} walletTransactionHistoryResponse
 * @property {CommonPaginatedResponse} - This section provides information about how the results are divided into pages.
 * @property {BytenitewalletTransaction[]}
 */
export type WalletTransactionHistoryResponse = z.infer<typeof walletTransactionHistoryResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const walletTransactionHistoryResponseResponse = z.lazy(() => {
  return z
    .object({
      pagination: commonPaginatedResponseResponse.optional(),
      data: z.array(bytenitewalletTransactionResponse).optional(),
    })
    .transform((data) => ({
      pagination: data['pagination'],
      data: data['data'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const walletTransactionHistoryResponseRequest = z.lazy(() => {
  return z
    .object({
      pagination: commonPaginatedResponseRequest.optional(),
      data: z.array(bytenitewalletTransactionRequest).optional(),
    })
    .transform((data) => ({
      pagination: data['pagination'],
      data: data['data'],
    }));
});
