// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const walletGeneratePayoutPortalLinkResponse = z.lazy(() => {
  return z.object({
    url: z.string().optional(),
  });
});

/**
 *
 * @typedef  {WalletGeneratePayoutPortalLinkResponse} walletGeneratePayoutPortalLinkResponse
 * @property {string}
 */
export type WalletGeneratePayoutPortalLinkResponse = z.infer<typeof walletGeneratePayoutPortalLinkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const walletGeneratePayoutPortalLinkResponseResponse = z.lazy(() => {
  return z
    .object({
      url: z.string().optional(),
    })
    .transform((data) => ({
      url: data['url'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const walletGeneratePayoutPortalLinkResponseRequest = z.lazy(() => {
  return z
    .object({
      url: z.string().optional(),
    })
    .transform((data) => ({
      url: data['url'],
    }));
});
