// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const walletApiRedeemCouponResponse = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    code: z.string().optional(),
    amount: z.string().optional(),
  });
});

/**
 *
 * @typedef  {WalletApiRedeemCouponResponse} walletApiRedeemCouponResponse
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type WalletApiRedeemCouponResponse = z.infer<typeof walletApiRedeemCouponResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const walletApiRedeemCouponResponseResponse = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      code: z.string().optional(),
      amount: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      code: data['code'],
      amount: data['amount'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const walletApiRedeemCouponResponseRequest = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      code: z.string().optional(),
      amount: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      code: data['code'],
      amount: data['amount'],
    }));
});
