// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const walletTransactionHistoryCsvResponse = z.lazy(() => {
  return z.object({
    csv: z.string().optional(),
  });
});

/**
 *
 * @typedef  {WalletTransactionHistoryCsvResponse} walletTransactionHistoryCsvResponse
 * @property {string}
 */
export type WalletTransactionHistoryCsvResponse = z.infer<typeof walletTransactionHistoryCsvResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const walletTransactionHistoryCsvResponseResponse = z.lazy(() => {
  return z
    .object({
      csv: z.string().optional(),
    })
    .transform((data) => ({
      csv: data['csv'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const walletTransactionHistoryCsvResponseRequest = z.lazy(() => {
  return z
    .object({
      csv: z.string().optional(),
    })
    .transform((data) => ({
      csv: data['csv'],
    }));
});
