// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const walletApiCancelTopUpRequestParams = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    cancelMessage: z.string().optional(),
  });
});

/**
 *
 * @typedef  {WalletApiCancelTopUpRequestParams} walletApiCancelTopUpRequestParams
 * @property {string}
 * @property {string}
 */
export type WalletApiCancelTopUpRequestParams = z.infer<typeof walletApiCancelTopUpRequestParams>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const walletApiCancelTopUpRequestParamsResponse = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      cancelMessage: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      cancelMessage: data['cancelMessage'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const walletApiCancelTopUpRequestParamsRequest = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      cancelMessage: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      cancelMessage: data['cancelMessage'],
    }));
});
