// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { WalletTopUpRequestState, walletTopUpRequestState } from './wallet-top-up-request-state';

/**
 * The shape of the model inside the application code - what the users use
 */
export const walletTopUpRequest = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
    ownerId: z.string().optional(),
    accountId: z.string().optional(),
    billingProfileId: z.string().optional(),
    amount: z.number().optional(),
    currency: z.string().optional(),
    currencyAmount: z.string().optional(),
    exchangeRate: z.number().optional(),
    state: walletTopUpRequestState.optional(),
    confirmImmediately: z.boolean().optional(),
    topupType: z.string().optional(),
    shouldDowngradeTier: z.boolean().optional(),
    shouldRecoverCompletely: z.boolean().optional(),
  });
});

/**
 *
 * @typedef  {WalletTopUpRequest} walletTopUpRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {number}
 * @property {string}
 * @property {string}
 * @property {number}
 * @property {WalletTopUpRequestState}
 * @property {boolean}
 * @property {string}
 * @property {boolean}
 * @property {boolean}
 */
export type WalletTopUpRequest = z.infer<typeof walletTopUpRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const walletTopUpRequestResponse = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      createdAt: z.string().optional(),
      updatedAt: z.string().optional(),
      ownerId: z.string().optional(),
      accountId: z.string().optional(),
      billingProfileId: z.string().optional(),
      amount: z.number().optional(),
      currency: z.string().optional(),
      currencyAmount: z.string().optional(),
      exchangeRate: z.number().optional(),
      state: walletTopUpRequestState.optional(),
      confirmImmediately: z.boolean().optional(),
      topupType: z.string().optional(),
      shouldDowngradeTier: z.boolean().optional(),
      shouldRecoverCompletely: z.boolean().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      createdAt: data['createdAt'],
      updatedAt: data['updatedAt'],
      ownerId: data['ownerId'],
      accountId: data['accountId'],
      billingProfileId: data['billingProfileId'],
      amount: data['amount'],
      currency: data['currency'],
      currencyAmount: data['currencyAmount'],
      exchangeRate: data['exchangeRate'],
      state: data['state'],
      confirmImmediately: data['confirmImmediately'],
      topupType: data['topupType'],
      shouldDowngradeTier: data['shouldDowngradeTier'],
      shouldRecoverCompletely: data['shouldRecoverCompletely'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const walletTopUpRequestRequest = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      createdAt: z.string().optional(),
      updatedAt: z.string().optional(),
      ownerId: z.string().optional(),
      accountId: z.string().optional(),
      billingProfileId: z.string().optional(),
      amount: z.number().optional(),
      currency: z.string().optional(),
      currencyAmount: z.string().optional(),
      exchangeRate: z.number().optional(),
      state: walletTopUpRequestState.optional(),
      confirmImmediately: z.boolean().optional(),
      topupType: z.string().optional(),
      shouldDowngradeTier: z.boolean().optional(),
      shouldRecoverCompletely: z.boolean().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      createdAt: data['createdAt'],
      updatedAt: data['updatedAt'],
      ownerId: data['ownerId'],
      accountId: data['accountId'],
      billingProfileId: data['billingProfileId'],
      amount: data['amount'],
      currency: data['currency'],
      currencyAmount: data['currencyAmount'],
      exchangeRate: data['exchangeRate'],
      state: data['state'],
      confirmImmediately: data['confirmImmediately'],
      topupType: data['topupType'],
      shouldDowngradeTier: data['shouldDowngradeTier'],
      shouldRecoverCompletely: data['shouldRecoverCompletely'],
    }));
});
