// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { AppsService } from './services/apps';
import { EnginesService } from './services/engines';
import { InfoService } from './services/info';
import { TemplatesService } from './services/templates';
import { TestsService } from './services/tests';

export * from './services/apps';
export * from './services/engines';
export * from './services/info';
export * from './services/templates';
export * from './services/tests';
export * from './services/common';

export * from './http';
export { Environment } from './http/environment';

export class ByteNiteDevelopersApi {
  public readonly apps: AppsService;

  public readonly engines: EnginesService;

  public readonly info: InfoService;

  public readonly templates: TemplatesService;

  public readonly tests: TestsService;

  constructor(public config: SdkConfig) {
    this.apps = new AppsService(this.config);

    this.engines = new EnginesService(this.config);

    this.info = new InfoService(this.config);

    this.templates = new TemplatesService(this.config);

    this.tests = new TestsService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.apps.baseUrl = baseUrl;
    this.engines.baseUrl = baseUrl;
    this.info.baseUrl = baseUrl;
    this.templates.baseUrl = baseUrl;
    this.tests.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.apps.baseUrl = environment;
    this.engines.baseUrl = environment;
    this.info.baseUrl = environment;
    this.templates.baseUrl = environment;
    this.tests.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.apps.timeoutMs = timeoutMs;
    this.engines.timeoutMs = timeoutMs;
    this.info.timeoutMs = timeoutMs;
    this.templates.timeoutMs = timeoutMs;
    this.tests.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.apps.token = token;
    this.engines.token = token;
    this.info.token = token;
    this.templates.token = token;
    this.tests.token = token;
  }

  set apiKey(apiKey: string) {
    this.apps.apiKey = apiKey;
    this.engines.apiKey = apiKey;
    this.info.apiKey = apiKey;
    this.templates.apiKey = apiKey;
    this.tests.apiKey = apiKey;
  }

  set apiKeyHeader(apiKeyHeader: string) {
    this.apps.apiKeyHeader = apiKeyHeader;
    this.engines.apiKeyHeader = apiKeyHeader;
    this.info.apiKeyHeader = apiKeyHeader;
    this.templates.apiKeyHeader = apiKeyHeader;
    this.tests.apiKeyHeader = apiKeyHeader;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
