// This file was generated by liblab | https://liblab.com/

import { ByteNiteJobsApi } from 'bytenite jobs api';

(async () => {
  const byteNiteJobsApi = new ByteNiteJobsApi({
    token: 'YOUR_TOKEN',
  });

  const { data } = await byteNiteJobsApi.jobs.customerGetAll({
    paginationLimit: 5,
    paginationOffset: 5,
    orderBy: 'orderBy',
  });

  console.log(data);
})();
