// This file was generated by liblab | https://liblab.com/

export interface CustomerGetAllParams {
  paginationLimit?: number;
  paginationOffset?: number;
  orderBy?: string;
}

export interface CustomerGetJobTemplatesParams {
  paginationLimit?: number;
  paginationOffset?: number;
}
