// This file was generated by liblab | https://liblab.com/

import { ByteNiteDevelopersApi } from 'bytenite developers api';

(async () => {
  const byteNiteDevelopersApi = new ByteNiteDevelopersApi({
    token: 'YOUR_TOKEN',
  });

  const { data } = await byteNiteDevelopersApi.apps.developerGetApps({
    orderBy: 'orderBy',
    paginationLimit: 5,
    paginationOffset: 2,
  });

  console.log(data);
})();
