// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  CommonDeviceRequirements,
  commonDeviceRequirements,
  commonDeviceRequirementsRequest,
  commonDeviceRequirementsResponse,
} from '../../common/common-device-requirements';
import {
  PlatformConfigRepresentsConfigurationForAPlatform,
  platformConfigRepresentsConfigurationForAPlatform,
  platformConfigRepresentsConfigurationForAPlatformRequest,
  platformConfigRepresentsConfigurationForAPlatformResponse,
} from '../../common/platform-config-represents-configuration-for-a-platform';

/**
 * The shape of the model inside the application code - what the users use
 */
export const byteniteappApp = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    version: z.string().optional(),
    owner: z.string().optional(),
    status: z.string().optional(),
    deviceRequirements: commonDeviceRequirements.optional(),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
    platform: z.string().optional(),
    hash: z.string().optional(),
    link: z.string().optional(),
    platformConfig: platformConfigRepresentsConfigurationForAPlatform.optional(),
    entrypoint: z.string().optional(),
    revision: z.string().optional(),
    description: z.string().optional(),
  });
});

/**
 *
 * @typedef  {ByteniteappApp} byteniteappApp
 * @property {string} - Unique identifier assigned to the distributed app (UUID).
 * @property {string} - Human-readable name of the app.
 * @property {string}
 * @property {string} - UUID of the user who owns the app.
 * @property {string} - Status of the app, e.g., active, inactive.
 * @property {CommonDeviceRequirements} - DeviceRequirements represents the minimum hardware requirements for running the app/engine.
 * @property {string} - UTC timestamp when the app was created.
 * @property {string} - UTC timestamp when the app was last updated.
 * @property {string} - Target platform for app execution (e.g., docker).
 * @property {string} - SHA256 checksum of the uploaded tar archive.
 * @property {string} - Reserved field for future use; currently contains metadata or download links.
 * @property {PlatformConfigRepresentsConfigurationForAPlatform}
 * @property {string} - Main executable file or script to launch the application (e.g., main.py).
 * @property {string} - Internal revision tracking number.
 * @property {string} - Optional free-form description of the app.
 */
export type ByteniteappApp = z.infer<typeof byteniteappApp>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const byteniteappAppResponse = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      version: z.string().optional(),
      owner: z.string().optional(),
      status: z.string().optional(),
      deviceRequirements: commonDeviceRequirementsResponse.optional(),
      createdAt: z.string().optional(),
      updatedAt: z.string().optional(),
      platform: z.string().optional(),
      hash: z.string().optional(),
      link: z.string().optional(),
      platformConfig: platformConfigRepresentsConfigurationForAPlatformResponse.optional(),
      entrypoint: z.string().optional(),
      revision: z.string().optional(),
      description: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      version: data['version'],
      owner: data['owner'],
      status: data['status'],
      deviceRequirements: data['deviceRequirements'],
      createdAt: data['createdAt'],
      updatedAt: data['updatedAt'],
      platform: data['platform'],
      hash: data['hash'],
      link: data['link'],
      platformConfig: data['platformConfig'],
      entrypoint: data['entrypoint'],
      revision: data['revision'],
      description: data['description'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const byteniteappAppRequest = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      version: z.string().optional(),
      owner: z.string().optional(),
      status: z.string().optional(),
      deviceRequirements: commonDeviceRequirementsRequest.optional(),
      createdAt: z.string().optional(),
      updatedAt: z.string().optional(),
      platform: z.string().optional(),
      hash: z.string().optional(),
      link: z.string().optional(),
      platformConfig: platformConfigRepresentsConfigurationForAPlatformRequest.optional(),
      entrypoint: z.string().optional(),
      revision: z.string().optional(),
      description: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      version: data['version'],
      owner: data['owner'],
      status: data['status'],
      deviceRequirements: data['deviceRequirements'],
      createdAt: data['createdAt'],
      updatedAt: data['updatedAt'],
      platform: data['platform'],
      hash: data['hash'],
      link: data['link'],
      platformConfig: data['platformConfig'],
      entrypoint: data['entrypoint'],
      revision: data['revision'],
      description: data['description'],
    }));
});
