// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const developerUploadAppRequest = z.lazy(() => {
  return z.object({
    data: z.string(),
  });
});

/**
 *
 * @typedef  {DeveloperUploadAppRequest} developerUploadAppRequest
 * @property {string} - Base64-encoded tar archive containing application code, configuration, and dependencies.
 */
export type DeveloperUploadAppRequest = z.infer<typeof developerUploadAppRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const developerUploadAppRequestResponse = z.lazy(() => {
  return z
    .object({
      data: z.string(),
    })
    .transform((data) => ({
      data: data['data'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const developerUploadAppRequestRequest = z.lazy(() => {
  return z
    .object({
      data: z.string(),
    })
    .transform((data) => ({
      data: data['data'],
    }));
});
