// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse, RequestConfig } from '../../http/types';
import { RequestBuilder } from '../../http/transport/request-builder';
import { SerializationStyle } from '../../http/serialization/base-serializer';
import { ThrowableError } from '../../http/errors/throwable-error';
import { Environment } from '../../http/environment';
import {
  StreamResultOfCustomerEvent,
  streamResultOfCustomerEventResponse,
} from './models/stream-result-of-customer-event';
import { RpcStatus } from '../common/rpc-status';

export class EventsService extends BaseService {
  /**
   * Listen events
   * @param {RequestConfig} requestConfig - (Optional) The request configuration for retry and validation.
   * @returns {Promise<HttpResponse<StreamResultOfCustomerEvent>>} A successful response.(streaming responses)
   */
  public async *customerEvents(
    requestConfig?: RequestConfig,
  ): AsyncGenerator<HttpResponse<StreamResultOfCustomerEvent>> {
    const request = new RequestBuilder()
      .setBaseUrl(requestConfig?.baseUrl || this.config.baseUrl || this.config.environment || Environment.DEFAULT)
      .setConfig(this.config)
      .setMethod('GET')
      .setPath('/events')
      .setRequestSchema(z.any())
      .addAccessTokenAuth(this.config.token, 'Bearer')
      .addApiKeyAuth(this.config.apiKey)
      .setRequestContentType(ContentType.Json)
      .addResponse({
        schema: streamResultOfCustomerEventResponse,
        contentType: ContentType.EventStream,
        status: 200,
      })
      .addError({
        error: ThrowableError,
        contentType: ContentType.EventStream,
        status: 400,
      })
      .addError({
        error: ThrowableError,
        contentType: ContentType.EventStream,
        status: 401,
      })
      .addError({
        error: ThrowableError,
        contentType: ContentType.EventStream,
        status: 403,
      })
      .addError({
        error: ThrowableError,
        contentType: ContentType.EventStream,
        status: 404,
      })
      .addError({
        error: ThrowableError,
        contentType: ContentType.EventStream,
        status: 500,
      })
      .addError({
        error: ThrowableError,
        contentType: ContentType.EventStream,
        status: 503,
      })
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .build();
    yield* this.client.stream<StreamResultOfCustomerEvent>(request);
  }
}
