// This file was generated by liblab | https://liblab.com/

export interface DeveloperGetEnginesParams {
  orderBy?: string;
  paginationLimit?: number;
  paginationOffset?: number;
}

export interface DeveloperUploadEngineParams {
  engineId?: string;
  engineTag?: string;
  engineData?: string;
  engineLink?: string;
  engineStatus?: string;
}

export interface DeveloperGetEngineByTagParams {
  engineId?: string;
  engineData?: string;
  engineLink?: string;
  engineStatus?: string;
}

export interface DeveloperActivateEngineParams {
  engineId?: string;
  engineData?: string;
  engineLink?: string;
  engineStatus?: string;
}

export interface DeveloperDeactivateEngineParams {
  engineId?: string;
  engineData?: string;
  engineLink?: string;
  engineStatus?: string;
}

export interface DeveloperGetEngineLinkParams {
  engineId?: string;
  engineData?: string;
  engineLink?: string;
  engineStatus?: string;
}

export interface DeveloperGetEngineStatusParams {
  engineId?: string;
  engineData?: string;
  engineLink?: string;
  engineStatus?: string;
}
