// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const commonSelectionList = z.lazy(() => {
  return z.object({
    blacklist: z.array(z.string()).optional(),
    whitelist: z.array(z.string()).optional(),
  });
});

/**
 *
 * @typedef  {CommonSelectionList} commonSelectionList
 * @property {string[]}
 * @property {string[]}
 */
export type CommonSelectionList = z.infer<typeof commonSelectionList>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const commonSelectionListResponse = z.lazy(() => {
  return z
    .object({
      blacklist: z.array(z.string()).optional(),
      whitelist: z.array(z.string()).optional(),
    })
    .transform((data) => ({
      blacklist: data['blacklist'],
      whitelist: data['whitelist'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const commonSelectionListRequest = z.lazy(() => {
  return z
    .object({
      blacklist: z.array(z.string()).optional(),
      whitelist: z.array(z.string()).optional(),
    })
    .transform((data) => ({
      blacklist: data['blacklist'],
      whitelist: data['whitelist'],
    }));
});
