// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  CommonLimitOffsetPagination,
  commonLimitOffsetPagination,
  commonLimitOffsetPaginationRequest,
  commonLimitOffsetPaginationResponse,
} from './common-limit-offset-pagination';
import { CommonFilter, commonFilter, commonFilterRequest, commonFilterResponse } from './common-filter';

/**
 * The shape of the model inside the application code - what the users use
 */
export const customerGetAllJobsRequest = z.lazy(() => {
  return z.object({
    pagination: commonLimitOffsetPagination.optional(),
    filters: z.array(commonFilter).optional(),
    orderBy: z.string().optional(),
  });
});

/**
 *
 * @typedef  {CustomerGetAllJobsRequest} customerGetAllJobsRequest
 * @property {CommonLimitOffsetPagination}
 * @property {CommonFilter[]}
 * @property {string}
 */
export type CustomerGetAllJobsRequest = z.infer<typeof customerGetAllJobsRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const customerGetAllJobsRequestResponse = z.lazy(() => {
  return z
    .object({
      pagination: commonLimitOffsetPaginationResponse.optional(),
      filters: z.array(commonFilterResponse).optional(),
      orderBy: z.string().optional(),
    })
    .transform((data) => ({
      pagination: data['pagination'],
      filters: data['filters'],
      orderBy: data['orderBy'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const customerGetAllJobsRequestRequest = z.lazy(() => {
  return z
    .object({
      pagination: commonLimitOffsetPaginationRequest.optional(),
      filters: z.array(commonFilterRequest).optional(),
      orderBy: z.string().optional(),
    })
    .transform((data) => ({
      pagination: data['pagination'],
      filters: data['filters'],
      orderBy: data['orderBy'],
    }));
});
