// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const customerJobsRunningTasksResponse = z.lazy(() => {
  return z.object({
    jobsRunningTasks: z.any().optional(),
  });
});

/**
 *
 * @typedef  {CustomerJobsRunningTasksResponse} customerJobsRunningTasksResponse
 * @property {any}
 */
export type CustomerJobsRunningTasksResponse = z.infer<typeof customerJobsRunningTasksResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const customerJobsRunningTasksResponseResponse = z.lazy(() => {
  return z
    .object({
      jobsRunningTasks: z.any().optional(),
    })
    .transform((data) => ({
      jobsRunningTasks: data['jobsRunningTasks'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const customerJobsRunningTasksResponseRequest = z.lazy(() => {
  return z
    .object({
      jobsRunningTasks: z.any().optional(),
    })
    .transform((data) => ({
      jobsRunningTasks: data['jobsRunningTasks'],
    }));
});
