// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const jobJobState = z.union([
  z.literal('JOB_STATE_NEW'),
  z.literal('JOB_STATE_STARTED'),
  z.literal('JOB_STATE_UPLOADING'),
  z.literal('JOB_STATE_PARTITIONING'),
  z.literal('JOB_STATE_PARTITIONED'),
  z.literal('JOB_STATE_TASKS_COMPLETED'),
  z.literal('JOB_STATE_MERGING'),
  z.literal('JOB_STATE_MERGED'),
  z.literal('JOB_STATE_DOWNLOADING'),
  z.literal('JOB_STATE_COMPLETE'),
  z.literal('JOB_STATE_FAILED'),
]);

export type JobJobState = z.infer<typeof jobJobState>;
