// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const jobByteLevel = z.union([
  z.literal('EXECUTION_PRIORITY_UNDEFINED'),
  z.literal('EXECUTION_PRIORITY_CHEAP'),
  z.literal('EXECUTION_PRIORITY_BALANCED'),
  z.literal('EXECUTION_PRIORITY_FAST'),
]);

export type JobByteLevel = z.infer<typeof jobByteLevel>;
