// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { JobJobConfig, jobJobConfig, jobJobConfigRequest, jobJobConfigResponse } from './job-job-config';

/**
 * The shape of the model inside the application code - what the users use
 */
export const jobsCustomerRunJobRequest1 = z.lazy(() => {
  return z.object({
    config: jobJobConfig.optional(),
  });
});

/**
 *
 * @typedef  {JobsCustomerRunJobRequest1} jobsCustomerRunJobRequest1
 * @property {JobJobConfig}
 */
export type JobsCustomerRunJobRequest1 = z.infer<typeof jobsCustomerRunJobRequest1>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const jobsCustomerRunJobRequest1Response = z.lazy(() => {
  return z
    .object({
      config: jobJobConfigResponse.optional(),
    })
    .transform((data) => ({
      config: data['config'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const jobsCustomerRunJobRequest1Request = z.lazy(() => {
  return z
    .object({
      config: jobJobConfigRequest.optional(),
    })
    .transform((data) => ({
      config: data['config'],
    }));
});
