// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  DataSourceDataSource,
  dataSourceDataSource,
  dataSourceDataSourceRequest,
  dataSourceDataSourceResponse,
} from './data-source-data-source';

/**
 * The shape of the model inside the application code - what the users use
 */
export const jobsDataSourceParams = z.lazy(() => {
  return z.object({
    dataSource: dataSourceDataSource.optional(),
    dataDestination: dataSourceDataSource.optional(),
  });
});

/**
 *
 * @typedef  {JobsDataSourceParams} jobsDataSourceParams
 * @property {DataSourceDataSource} - The data source object specifying configurations for inputs and outputs. Please refer to the dedicated guide for detailed instructions.
 * @property {DataSourceDataSource} - The data source object specifying configurations for inputs and outputs. Please refer to the dedicated guide for detailed instructions.
 */
export type JobsDataSourceParams = z.infer<typeof jobsDataSourceParams>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const jobsDataSourceParamsResponse = z.lazy(() => {
  return z
    .object({
      dataSource: dataSourceDataSourceResponse.optional(),
      dataDestination: dataSourceDataSourceResponse.optional(),
    })
    .transform((data) => ({
      dataSource: data['dataSource'],
      dataDestination: data['dataDestination'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const jobsDataSourceParamsRequest = z.lazy(() => {
  return z
    .object({
      dataSource: dataSourceDataSourceRequest.optional(),
      dataDestination: dataSourceDataSourceRequest.optional(),
    })
    .transform((data) => ({
      dataSource: data['dataSource'],
      dataDestination: data['dataDestination'],
    }));
});
