// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  CommonPaginatedResponse,
  commonPaginatedResponse,
  commonPaginatedResponseRequest,
  commonPaginatedResponseResponse,
} from './common-paginated-response';
import { JobJobTemplate, jobJobTemplate, jobJobTemplateRequest, jobJobTemplateResponse } from './job-job-template';

/**
 * The shape of the model inside the application code - what the users use
 */
export const jobsJobTemplatesResponse = z.lazy(() => {
  return z.object({
    pagination: commonPaginatedResponse.optional(),
    data: z.array(jobJobTemplate).optional(),
  });
});

/**
 *
 * @typedef  {JobsJobTemplatesResponse} jobsJobTemplatesResponse
 * @property {CommonPaginatedResponse} - This section provides information about how the results are divided into pages.
 * @property {JobJobTemplate[]}
 */
export type JobsJobTemplatesResponse = z.infer<typeof jobsJobTemplatesResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const jobsJobTemplatesResponseResponse = z.lazy(() => {
  return z
    .object({
      pagination: commonPaginatedResponseResponse.optional(),
      data: z.array(jobJobTemplateResponse).optional(),
    })
    .transform((data) => ({
      pagination: data['pagination'],
      data: data['data'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const jobsJobTemplatesResponseRequest = z.lazy(() => {
  return z
    .object({
      pagination: commonPaginatedResponseRequest.optional(),
      data: z.array(jobJobTemplateRequest).optional(),
    })
    .transform((data) => ({
      pagination: data['pagination'],
      data: data['data'],
    }));
});
